apiVersion: v1
kind: ConfigMap
metadata:
  name: chapchu-auth-config
  namespace: chapchu
data:
  AUTH_SERVER_URL: "https://auth.chapchu.site"
  GOOGLE_REDIRECT_URI: "https://auth.chapchu.site/login/oauth2/code/google"
  FRONT_REDIRECT_URI: "http://localhost:3000/login/callback"
