apiVersion: v1
kind: ConfigMap
metadata:
  name: chapchu-auth-config
  namespace: chapchu
data:
  AUTH_SERVER_URL: "http://auth.chapchu.site"
  FRONT_REDIRECT_URI: "http://<FRONT_DOMAIN>/login/callback"
